openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: "1.0"
servers:
  - url: https://jobs-api-bhe.herokuapp.com/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: REGISTER USER
      operationId: REGISTERUSER
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              example:
                name: billy
                email: billy@gmail.com
                password: guessmypassword
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /auth/login:
    post:
      tags:
        - Auth
      summary: LOGIN USER
      operationId: LOGINUSER
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LOGINUSERREQUEST"
            example:
              email: billy@gmail.com
              password: guessmypassword
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /jobs:
    post:
      tags:
        - Jobs
      summary: CREATE JOB
      operationId: CREATEJOB
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CREATEJOBREQUEST"
            example:
              company: YUKON DEV
              position: FULLSTACK DEV
              salary: 9922HAAB
              location: YUKON
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    get:
      tags:
        - Jobs
      summary: GET ALL JOBS
      operationId: GETALLJOBS
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: the job id
    get:
      tags:
        - Jobs
      summary: GET SINGLE JOB
      operationId: GETSINGLEJOB
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []

    patch:
      tags:
        - Jobs
      summary: UPDATE JOB
      operationId: UPDATEJOB
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UPDATEJOBREQUEST"
            example:
              company: BHE Tech Industries
              position: COO
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []

    delete:
      tags:
        - Jobs
      summary: DELETE JOB
      operationId: DELETEJOB
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    LOGINUSERREQUEST:
      title: LOGINUSERREQUEST
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: bhea1@gmail.com
        password: "123456"
    CREATEJOBREQUEST:
      title: CREATEJOBREQUEST
      required:
        - company
        - position
        - salary
        - location
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        salary:
          type: string
        location:
          type: string
      example:
        company: YUKON DEV
        position: FULLSTACK DEV
        salary: 9922HAAB
        location: YUKON
    UPDATEJOBREQUEST:
      title: UPDATEJOBREQUEST
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: yukon dev comapny 2
        position: COO
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: ""
  - name: Jobs
    description: ""
